### ISSUE TITLE
"Too many open files" crashes the kvs

### ISSUE THREAD

**Issue by authwork** [hydro-project/anna#38]
I encounter the following issue:
```
terminate called after throwing an instance of 'zmq::error_t'
  what():  Too many open files
bash: line 1: 20404 Aborted                 ./build/target/kvs/anna-kvs
terminate called after throwing an instance of 'zmq::error_t'
  what():  Too many open files
bash: line 1: 32208 Aborted                 ./build/target/kvs/anna-kvs
```

**Comment by authwork** [comment]
I also encounter this issue, To get the value of the same key, it sometimes can read the value, sometimes cannot.
![image](https://user-images.githubusercontent.com/29809742/80351851-95a7b980-88a5-11ea-8f18-4ed44bf0eccb.png)

**Comment by authwork** [comment]
3. Is there any detail steps to run the anna-bench for evaluating the performance of the system?

**Comment by authwork** [comment]
All these issues do not appear in Anna local mode, I guess it may be caused by the configuration of the Anna Cluster mode.
Would you mind giving some correct examples of cluster configuration, e.g. use 4 nodes for 3 replications in memory?
@vsreekanti 
Many thanks

**Comment by vsreekanti** [comment]
Hm, this is a surprising error. It isn't something I've seen before. Is this error occurring for disk nodes or memory nodes? It's unclear what the file descriptors are being created for, unless you're using a very large number of clients.

**Comment by authwork** [comment]
I am running a 8 nodes server and 64 clients to access those replicas.
I only uses memory node.

**Comment by authwork** [comment]
It has one more issue in N replicas.
The PUT needs time to sync to all other replica, and GET will random choose one replica, which may not be synchronized and does not have this key-value pair.
```
kvs> PUTSUM weight 1                 
Success!                                                 
kvs> GETSUM weight                                  
0                                                        
7                                                        
0                                                        
0,                                                    
kvs> GETSUM weight                               
7                                                        
7                                                        
1                                                  
1, 1      
```

**Comment by vsreekanti** [comment]
Sharing a single seed IP is okay. It sounds like the `ulimit` for open FDs on the machine you are running on is too low. Can you try increasing the `ulimit`? My hunch is that all 64 clients are talking to all nodes and as a result, there process is running into a limit for the number of allowed open sockets. That's why only using 16 clients works -- the aggregate number of clients is lower.

**Comment by authwork** [comment]
@vsreekanti  Many thanks for your help.
Hello! Increasing the ```ulimit``` (see [here](https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu)) solved the "Too many files" issue.
Now, the cluster of 1 server node and 64 clients works normal.

However, the cluster of 8 server nodes and 64 clients remains some issues:
I am a little confused:
1. Is it necessary to run the monitors in Anna cluster mode? 
In my pervious experiments (the cluster of 1 server node and 64 clients), we do not run the monitors and it works normal. I am not very sure whether we do not need to run monitors in the cluster of 8 server nodes and 64 clients.

2. The ```mgmt_ip``` of monitoring ("127.0.0.1" by default) and the ```mgmt_ip``` of server ("NULL" by default)

Currently, I guess that it is not necessary to run the monitors, and I set all monitor-related to "127.0.0.1". In the first step, I configure 8 replications on 8 server nodes.
My configuration files are shown below:
![image](https://user-images.githubusercontent.com/29809742/80566896-91ef7080-8a26-11ea-862f-cbc1407e26d9.png)
Would you please give some suggestions?

**Comment by vsreekanti** [comment]
1. Regarding running the monitoring node, it should not be necessary. However, the system will not increase/decrease the number of replicas of each key in response to load change if that is a feature you would like.

2. You can ignore the `mgmt_ip` as well -- it's used for Kubernetes autoscaling.

3. Public IPs and private IPs are used when running in VPCs (e.g., for EC2). All internal communication is done on private IPs, and request handling is done on public IPs. If you are not running in a VPC or don't need KVS access outside the VPC, you can just use the same IP address for both.

Regarding R2 not being able to read the KV pair, this is *expected behavior*. That is the nature of the coordination-freeness of the system, that you may read stale values (including `NULL` as a value). If you want more deterministic behavior, you can try making a client sticky to a single replica for a particular key by changing the KVS client, but that is not something we currently support out of the box.

1. You can make multiple requests then call `receive` if that workflow is more convenient for you.

2. When do you mean by the speed of batch of operations? Are you seeing that batches of operations are particularly slow?

**Comment by authwork** [comment]
1. If I make multiple GET requests, how can I match each response to each key~(may be based on the ID returned by the requests instantly)
2. I just want it to be faster, make multiple requests then call ```receive``` seems to work like pipeline

Many thanks, I will take more try.

**Comment by authwork** [comment]
> 1. Regarding running the monitoring node, it should not be necessary. However, the system will not increase/decrease the number of replicas of each key in response to load change if that is a feature you would like.
> 2. You can ignore the `mgmt_ip` as well -- it's used for Kubernetes autoscaling.
> 3. Public IPs and private IPs are used when running in VPCs (e.g., for EC2). All internal communication is done on private IPs, and request handling is done on public IPs. If you are not running in a VPC or don't need KVS access outside the VPC, you can just use the same IP address for both.
> 
> Regarding R2 not being able to read the KV pair, this is _expected behavior_. That is the nature of the coordination-freeness of the system, that you may read stale values (including `NULL` as a value). If you want more deterministic behavior, you can try making a client sticky to a single replica for a particular key by changing the KVS client, but that is not something we currently support out of the box.
> 
> 1. You can make multiple requests then call `receive` if that workflow is more convenient for you.
> 2. When do you mean by the speed of batch of operations? Are you seeing that batches of operations are particularly slow?

Yes, in my current cluster configuration (shown before), both ```PUT``` and ```GET``` operation caused long delay.
